[package]
name = "winderoo-esp32"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
winderoo-embassy = { path = "../osww-embassy", default-features = false, features = ["esp32"] }
winderoo-firmware = { path = "../osww-firmware", default-features = false }

embassy-executor = "0.9"
embassy-time = { version = "0.5", features = ["tick-hz-1_000_000"] }
embassy-net = { version = "0.7", default-features = false, features = ["tcp", "udp", "dhcpv4", "dns"] }
embassy-sync = "0.7"

esp-hal = { version = "1.0", features = ["esp32", "unstable"] }
esp-rtos = { version = "0.2.0", features = ["esp32", "embassy", "esp-radio", "esp-alloc"] }
esp-radio = { version = "0.17", features = ["esp32", "wifi", "unstable"] }

esp-alloc = "0.9.0"
esp-println = { version = "0.16.1", default-features = false, features = ["esp32", "uart", "log-04"] }
esp-backtrace = { version = "0.18.1", default-features = false, features = ["esp32", "panic-handler", "println"] }
esp-storage = { version = "0.8.1", features = ["esp32"] }

esp-hal-dhcp-server = "0.2.7"
picoserve = { version = "0.17.1", default-features = false, features = ["alloc", "embassy", "log"] }
static_cell = "2.1.0"
edge-mdns = { version = "0.7.0", default-features = false, features = ["io", "log"], optional = true }
edge-nal-embassy = { version = "0.8.0", default-features = false, features = ["proto-ipv4", "udp", "multicast", "log"], optional = true }
embassy-ha = { version = "0.2.0", optional = true }

log = "0.4"
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embedded-storage = "0.3"

[features]
default = ["mdns"]
mdns = ["dep:edge-mdns", "dep:edge-nal-embassy"]
oled = ["winderoo-embassy/oled"]
home-assistant = ["dep:embassy-ha"]
