/**
 * OLED Display Renderer for the Winderoo Simulator
 *
 * This is a THIN RENDERER ONLY - it just displays pixels from a buffer.
 * The actual display content is rendered in Rust using the SAME embedded-graphics
 * code as the real firmware (see src/display.rs).
 *
 * This ensures pixel-perfect accuracy between simulator and real hardware.
 */

// SSD1306 display dimensions
export const DISPLAY_WIDTH = 128;
export const DISPLAY_HEIGHT = 64;

// Pixel scale for rendering (each OLED pixel becomes NxN canvas pixels)
const PIXEL_SCALE = 3;

// Colors - SSD1306 is monochrome but typically has a blue or white tint
const PIXEL_ON_COLOR = '#00E5FF'; // Cyan-blue like real OLED
const PIXEL_OFF_COLOR = '#0a0a12';
const BACKGROUND_COLOR = '#050508';

/**
 * OLED Display Renderer
 *
 * This class just renders a pixel buffer to canvas.
 * The pixel buffer comes from Rust code that uses the SAME
 * embedded-graphics rendering as the real hardware.
 */
export class OledDisplay {
  private canvas: HTMLCanvasElement;
  private ctx: CanvasRenderingContext2D;
  private glowCanvas: HTMLCanvasElement;
  private glowCtx: CanvasRenderingContext2D;

  constructor(container: HTMLElement | null) {
    // Create main canvas
    this.canvas = document.createElement('canvas');
    this.canvas.width = DISPLAY_WIDTH * PIXEL_SCALE;
    this.canvas.height = DISPLAY_HEIGHT * PIXEL_SCALE;
    this.canvas.style.imageRendering = 'pixelated';
    this.canvas.style.borderRadius = '4px';

    // Create glow canvas (for OLED bloom effect)
    this.glowCanvas = document.createElement('canvas');
    this.glowCanvas.width = DISPLAY_WIDTH * PIXEL_SCALE;
    this.glowCanvas.height = DISPLAY_HEIGHT * PIXEL_SCALE;
    this.glowCanvas.style.position = 'absolute';
    this.glowCanvas.style.top = '0';
    this.glowCanvas.style.left = '0';
    this.glowCanvas.style.pointerEvents = 'none';
    this.glowCanvas.style.filter = 'blur(4px)';
    this.glowCanvas.style.opacity = '0.3';
    this.glowCanvas.style.mixBlendMode = 'screen';

    const ctx = this.canvas.getContext('2d');
    const glowCtx = this.glowCanvas.getContext('2d');
    if (!ctx || !glowCtx) throw new Error('Could not get canvas context');
    this.ctx = ctx;
    this.glowCtx = glowCtx;

    // Create wrapper if container provided
    if (container) {
      const wrapper = document.createElement('div');
      wrapper.style.position = 'relative';
      wrapper.style.display = 'inline-block';
      wrapper.style.background = '#0a0a12';
      wrapper.style.padding = '8px';
      wrapper.style.borderRadius = '8px';
      wrapper.style.boxShadow = '0 0 20px rgba(0, 229, 255, 0.15), inset 0 0 10px rgba(0,0,0,0.5)';
      wrapper.appendChild(this.canvas);
      wrapper.appendChild(this.glowCanvas);
      container.appendChild(wrapper);
    }

    this.renderBlank();
  }

  /**
   * Get the canvas element for use as a texture
   */
  getCanvas(): HTMLCanvasElement {
    return this.canvas;
  }

  /**
   * Render a blank (off) display
   */
  renderBlank(): void {
    this.ctx.fillStyle = BACKGROUND_COLOR;
    this.ctx.fillRect(0, 0, this.canvas.width, this.canvas.height);
    this.glowCtx.clearRect(0, 0, this.glowCanvas.width, this.glowCanvas.height);
  }

  /**
   * Render a pixel buffer from the WASM simulator.
   *
   * The buffer is a Uint8Array of 128*64 = 8192 bytes where each byte is 0 (off) or 1 (on).
   * This buffer is generated by Rust code using the SAME embedded-graphics rendering
   * as the real firmware's Ssd1306Display.
   *
   * @param buffer - Pixel buffer from simulator.getDisplayBuffer()
   */
  renderBuffer(buffer: Uint8Array): void {
    // Clear canvases
    this.ctx.fillStyle = BACKGROUND_COLOR;
    this.ctx.fillRect(0, 0, this.canvas.width, this.canvas.height);
    this.glowCtx.clearRect(0, 0, this.glowCanvas.width, this.glowCanvas.height);

    // Draw each pixel from the buffer
    for (let y = 0; y < DISPLAY_HEIGHT; y++) {
      for (let x = 0; x < DISPLAY_WIDTH; x++) {
        const idx = y * DISPLAY_WIDTH + x;
        const pixelOn = buffer[idx] !== 0;
        const canvasX = x * PIXEL_SCALE;
        const canvasY = y * PIXEL_SCALE;

        if (pixelOn) {
          // Pixel is on
          this.ctx.fillStyle = PIXEL_ON_COLOR;
          const gap = PIXEL_SCALE > 2 ? 1 : 0;
          this.ctx.fillRect(canvasX, canvasY, PIXEL_SCALE - gap, PIXEL_SCALE - gap);

          // Draw glow
          this.glowCtx.fillStyle = PIXEL_ON_COLOR;
          this.glowCtx.fillRect(canvasX, canvasY, PIXEL_SCALE, PIXEL_SCALE);
        } else {
          // Pixel is off - subtle grid
          this.ctx.fillStyle = PIXEL_OFF_COLOR;
          this.ctx.fillRect(canvasX, canvasY, PIXEL_SCALE - 1, PIXEL_SCALE - 1);
        }
      }
    }
  }

  /**
   * Get display dimensions
   */
  get width(): number {
    return DISPLAY_WIDTH;
  }

  get height(): number {
    return DISPLAY_HEIGHT;
  }

  get canvasWidth(): number {
    return DISPLAY_WIDTH * PIXEL_SCALE;
  }

  get canvasHeight(): number {
    return DISPLAY_HEIGHT * PIXEL_SCALE;
  }
}
